### PR TITLE
Support for socket.io 1.x.x

### PR DESCRIPTION
**Pull request by mattdodge**

### CODE REVIEW

**Comment by hansmosh** [comment]
It's looking good, but it seems unlike you to have not created a common base class for the two clients. 

I assume this has been tested manually but I'm also surprised to not see an tests for the client_1. Is there an easy way to run the same (or similar) tests but patched with the other client?

**Comment by mattdodge** [comment]
Yeah, unfortunately there aren't really any tests for the client. The current tests mainly test how the block interacts with the client and assume the client works. So not only are there no tests for client_1 but also for client. I definitely don't think our test coverage is great in this block, but I don't think the addition of v1 makes it any worse. There probably could be a couple tests to make sure the right client gets used, but testing the clients is going to be way more involved.

**Comment by mattdodge** [comment]
Regarding the base class, right now v0 is the base class and v1 inherits. The v1 client could remove some of it's calls since a lot are just repeats of the parent class.

**Comment by hansmosh** [comment]
Ok cool. I didn't noticed that v0 was the base block.

**Comment by mattdodge** [comment]
Added this PR #23 that simplifies some of the client v1 - no functional or test changes, just cleanup

**Pull request merged**
